import type { IRTable, IRField, DdlDialect } from './ddlTypes'
import type { DdlOptions } from './ddlOptions'

function quote(name: string, dialect: DdlDialect, options: DdlOptions): string {
  if (!options.quoteIdentifiers) return name
  if (dialect === 'postgresql') return `"${name}"`
  return `\`${name}\``
}

function renderFieldType(field: IRField, dialect: DdlDialect, options: DdlOptions): string {
  const dbType = field.rawDbType || guessDbType(field, dialect, options)
  const parts = [dbType]

  if (field.unsigned) parts.push('UNSIGNED')
  if (field.charset && !field.columnName.includes('_')) parts.push(`CHARACTER SET ${field.charset}`)
  if (field.collation) parts.push(`COLLATE ${field.collation}`)

  return parts.join(' ')
}

function guessDbType(field: IRField, dialect: DdlDialect, options: DdlOptions): string {
  const jt = field.javaType
  const len = field.length
  if (dialect === 'postgresql') {
    return pgGuess(jt, len, options)
  }
  return mysqlGuess(jt, len, field.unsigned, field.enumValues, options)
}

function mysqlGuess(jt: string, len?: number, unsigned?: boolean, enumVals?: string[], options?: DdlOptions): string {
  switch (jt) {
    case 'Boolean': return len ? 'TINYINT(1)' : options?.mysqlBoolAsBit ? 'BIT(1)' : 'TINYINT(1)'
    case 'Byte': return 'TINYINT'
    case 'Short': return 'SMALLINT'
    case 'Integer': return unsigned ? 'INT UNSIGNED' : 'INT'
    case 'Long': return unsigned ? 'BIGINT UNSIGNED' : 'BIGINT'
    case 'Float': return 'FLOAT'
    case 'Double': return 'DOUBLE'
    case 'BigDecimal': {
      const ps = options?.defaultDecimalPS || '19,4'
      return `DECIMAL(${ps})`
    }
    case 'BigInteger': return 'DECIMAL(38,0)'
    case 'String': {
      if (enumVals && enumVals.length > 0) return `ENUM(${enumVals.map(v => `'${v}'`).join(',')})`
      if (len && len > 4000) return 'TEXT'
      if (len) return `VARCHAR(${len})`
      return 'VARCHAR(255)'
    }
    case 'LocalDate': return 'DATE'
    case 'LocalDateTime': return 'DATETIME'
    case 'LocalTime': return 'TIME'
    case 'OffsetDateTime': return 'TIMESTAMP'
    case 'OffsetTime': return 'TIME'
    case 'UUID': return options?.mysqlUuidAsBinary ? 'BINARY(16)' : 'VARCHAR(36)'
    case 'byte[]': return 'BLOB'
    default: return 'VARCHAR(255)'
  }
}

function pgGuess(jt: string, len?: number, options?: DdlOptions): string {
  switch (jt) {
    case 'Boolean': return 'BOOLEAN'
    case 'Byte': return 'SMALLINT'
    case 'Short': return 'SMALLINT'
    case 'Integer': return 'INTEGER'
    case 'Long': return 'BIGINT'
    case 'Float': return 'REAL'
    case 'Double': return 'DOUBLE PRECISION'
    case 'BigDecimal': {
      const ps = options?.defaultDecimalPS || '19,4'
      return `NUMERIC(${ps})`
    }
    case 'BigInteger': return 'NUMERIC(38,0)'
    case 'String': {
      if (len && len > 4000) return 'TEXT'
      if (options?.pgPreferText) return 'TEXT'
      if (len) return `VARCHAR(${len})`
      return 'VARCHAR(255)'
    }
    case 'LocalDate': return 'DATE'
    case 'LocalDateTime': return 'TIMESTAMP'
    case 'LocalTime': return 'TIME'
    case 'OffsetDateTime': return 'TIMESTAMP WITH TIME ZONE'
    case 'OffsetTime': return 'TIME WITH TIME ZONE'
    case 'UUID': return 'UUID'
    case 'byte[]': return 'BYTEA'
    default: return 'VARCHAR(255)'
  }
}

function renderDefault(field: IRField, dialect: DdlDialect): string {
  if (field.defaultValue === undefined || field.defaultValue === null) return ''
  const dv = field.defaultValue
  if (typeof dv === 'string' && dv.toUpperCase() === 'CURRENT_TIMESTAMP') {
    return `DEFAULT ${dialect === 'postgresql' ? 'CURRENT_TIMESTAMP' : 'CURRENT_TIMESTAMP'}`
  }
  if (typeof dv === 'string' && /^[\d.]+$/.test(dv)) return `DEFAULT ${dv}`
  return `DEFAULT '${dv}'`
}

function renderOnUpdate(field: IRField): string {
  if (!field.onUpdateCurrentTimestamp) return ''
  return 'ON UPDATE CURRENT_TIMESTAMP'
}

function renderInlinePk(field: IRField, dialect: DdlDialect): string {
  if (!field.primaryKey) return ''
  if (dialect === 'postgresql') return ''  // PKs as table constraint
  return 'PRIMARY KEY'
}

function renderAutoIncrement(field: IRField, dialect: DdlDialect, options: DdlOptions): string {
  if (!field.autoIncrement) return ''
  if (dialect === 'postgresql') {
    if (options.pgAutoIncrementStyle === 'serial') {
      return ''  // will use SERIAL type
    }
    return 'GENERATED BY DEFAULT AS IDENTITY'
  }
  return 'AUTO_INCREMENT'
}

function pgAutoTypeOverride(field: IRField, options: DdlOptions): string | null {
  if (!field.autoIncrement || !field.primaryKey) return null
  if (options.pgAutoIncrementStyle === 'serial') {
    const jt = field.javaType
    if (jt === 'Long' || jt === 'long') return 'BIGSERIAL'
    return 'SERIAL'
  }
  return null
}

function renderFieldConstraint(field: IRField): string {
  const parts: string[] = []
  if (field.unique) parts.push('UNIQUE')
  if (!field.nullable && !field.primaryKey) parts.push('NOT NULL')
  if (field.nullable && !field.primaryKey && field.defaultValue === undefined) parts.push('NULL')
  return parts.join(' ')
}

export function renderTableDdl(table: IRTable, dialect: DdlDialect, options: DdlOptions): string {
  const q = (name: string) => quote(name, dialect, options)
  const lines: string[] = []

  const engineClause = dialect === 'mysql' && options.mysqlEmitEngine && table.engine
    ? ` ENGINE=${table.engine}`
    : ''

  const charsetClause = table.charset ? ` DEFAULT CHARSET=${table.charset}` : ''
  const collationClause = table.collation ? ` COLLATE=${table.collation}` : ''

  if (options.commentToJavaDoc && table.comment) {
    lines.push(`-- ${table.comment}`)
  }

  lines.push(`CREATE TABLE ${q(table.tableName)} (`)

  const colDefs: string[] = []

  for (const field of table.fields) {
    const parts: string[] = [`  ${q(field.columnName)}`]

    if (dialect === 'postgresql') {
      const pgOverride = pgAutoTypeOverride(field, options)
      if (pgOverride) {
        parts.push(pgOverride)
      } else {
        parts.push(renderFieldType(field, dialect, options))
      }
    } else {
      parts.push(renderFieldType(field, dialect, options))
    }

    if (dialect !== 'postgresql') {
      const ai = renderAutoIncrement(field, dialect, options)
      if (ai) parts.push(ai)
    }

    const def = renderDefault(field, dialect)
    if (def) parts.push(def)

    const onUpd = renderOnUpdate(field)
    if (onUpd) parts.push(onUpd)

    const constraint = renderFieldConstraint(field)
    if (constraint) parts.push(constraint)

    const pk = renderInlinePk(field, dialect)
    if (pk) parts.push(pk)

    if (dialect === 'postgresql') {
      const ai = renderAutoIncrement(field, dialect, options)
      if (ai) parts.push(ai)
    }

    if (field.comment) {
      parts.push(`COMMENT '${field.comment.replace(/'/g, "''")}'`)
    }

    colDefs.push(parts.join(' '))
  }

  const pkColumns = table.primaryKey.filter((pk) => {
    if (dialect === 'postgresql') return true
    const field = table.fields.find(f => f.columnName === pk)
    return !field?.primaryKey
  })

  if (pkColumns.length > 0) {
    const pkStr = pkColumns.map(c => q(c)).join(', ')
    colDefs.push(`  PRIMARY KEY (${pkStr})`)
  }

  if (options.emitIndexes && table.indexes.length > 0) {
    for (const idx of table.indexes) {
      const colStr = idx.columns.map(c => q(c.columnName) + (c.order === 'desc' ? ' DESC' : '')).join(', ')
      const idxName = idx.name || `idx_${idx.columns.map(c => c.columnName).join('_')}`
      const unique = idx.unique ? 'UNIQUE ' : ''
      let idxType = ''
      if (idx.type === 'fulltext') idxType = 'FULLTEXT '
      else if (idx.type === 'hash' && dialect === 'mysql') idxType = 'USING HASH '
      colDefs.push(`  ${unique}${idxType}INDEX ${q(idxName)} (${colStr})`)
    }
  }

  lines.push(colDefs.join(',\n'))
  lines.push(`)${engineClause}${charsetClause}${collationClause};`)

  if (table.comment && !options.commentToJavaDoc) {
    if (dialect === 'postgresql') {
      lines.push(`COMMENT ON TABLE ${q(table.tableName)} IS '${table.comment.replace(/'/g, "''")}';`)
    } else {
      lines.push(`ALTER TABLE ${q(table.tableName)} COMMENT = '${table.comment.replace(/'/g, "''")}';`)
    }
  }

  for (const field of table.fields) {
    if (field.comment) {
      if (dialect === 'postgresql') {
        lines.push(`COMMENT ON COLUMN ${q(table.tableName)}.${q(field.columnName)} IS '${field.comment.replace(/'/g, "''")}';`)
      }
    }
  }

  return lines.join('\n')
}

export function renderDdl(tables: IRTable[], dialect: DdlDialect, options: DdlOptions): string {
  return tables.map(t => renderTableDdl(t, dialect, options)).join('\n\n')
}
